#!/bin/bash
host=denver.cs.colostate.edu
tar -cvf overlay.tar *
scp overlay.tar brandtr@$host:~/cs455/Overlay/
ssh brandtr@$host 'cd ~/cs455/Overlay/ && tar -xvf overlay.tar && rm overlay.tar'
rm overlay.tar
